### ISSUE TITLE
Support needed for Amazon Linux 2017.03

### ISSUE THREAD

**Issue by jamiegs** [signalfx/chef_install_configure_collectd#43]
Currently it fails to run if you're trying to install it on Amazon Linux version  2017.03.

**Comment by charliesignalfx** [comment]
Thank you for reporting this!  We will investigate and respond when a solution is available.

**Comment by jamiegs** [comment]
What sort of timeline is there on this? We'd like to move to the newer version of Amazon Linux and there doesn't appear to be any way to work around this issue.

**Comment by molner** [comment]
Hi @jamiegs. I don't have a timeline on this support yet, but hopefully it will be relatively soon. I will update this issue when we have a committed ETA.

**Comment by keitwb** [comment]
@jamiegs the new cookbook is pushed to the Supermarket and is here in this repo.  It is version 0.3.3.  Let us know if you have any further issues.
