### ISSUE TITLE
License in metadata

### ISSUE THREAD

**Issue by iennae** [signalfx/chef_install_configure_collectd#46]
Hey folks,

You have an "All Rights Reserved" license in https://github.com/signalfx/chef_install_configure_collectd/blob/master/metadata.rb and also publishing to the public supermarket at supermarket.chef.io. This kind of defeats the purpose of publishing the cookbook to the supermarket as it's saying folks can't use it. Did you folks mean to share the cookbook with the public or is the licensing the wrong one? 

https://choosealicense.com/ may help you select the appropriate license that allows folks to use the cookbook as well. 
 
Thanks for your attention to this.

**Comment by molner** [comment]
Thank you for bringing this to our attention, @iennae . This wasn't set that way by design, and the oversight has now been addressed to reflect the true license (Apache 2.0).

**Comment by iennae** [comment]
Awesome. thanks for this!
